In [1]:
#%matplotlib inline


# Plot Transformed Cylinders

Plots surfaces of transformed cylindrical shells.


In [7]:
print(__doc__)

import numpy as np
import matplotlib.pyplot as plt
from pytransform3d.transformations import transform_from, plot_transform
from pytransform3d.rotations import random_axis_angle, matrix_from_axis_angle
from pytransform3d.plot_utils import plot_cylinder, remove_frame

Automatically created module for IPython interactive environment


In [8]:
# Rotation 
R_pc = np.eye(3,3)
print('\n')
print('R_pc = ', np.array2string(R_pc, prefix='Array:  '))
# Translation 
t_pc = np.array([[1.5],[1],[1/2]]) 
print('\n')
print('t_pc = ', np.array2string(t_pc, prefix='Array:  '))



R_pc =  [[1. 0. 0.]
         [0. 1. 0.]
         [0. 0. 1.]]


t_pc =  [[1.5]
         [1. ]
         [0.5]]


In [9]:
T_pc = np.block([[R_pc,                     t_pc],
                [np.zeros((1, 3)),             1]])
print('T_pc = ', np.array2string(T_pc, prefix='Array:  '))

T_pc =  [[1.  0.  0.  1.5]
         [0.  1.  0.  1. ]
         [0.  0.  1.  0.5]
         [0.  0.  0.  1. ]]


In [10]:
ax = make_3d_axis(ax_s=1)

plot_transform(ax=ax, A2B = np.eye(4), s=1, lw=3)

plot_transform(ax=ax, A2B = T_pc, s=1, lw=3)


#plot_transform(ax=ax, A2B=A2B, s=0.3, lw=3)
ax.set_xlim((-2, 2))
ax.set_ylim((-1, 2))
ax.set_zlim((-2, 2))
plt.show()

NameError: name 'make_3d_axis' is not defined

In [11]:
import matplotlib.pyplot as plt
from pytransform3d.transformations import plot_transform
from pytransform3d.plot_utils import make_3d_axis

ax = make_3d_axis(ax_s=1, n_ticks=6)



plot_transform(ax=ax, np.eye(4))



plt.tight_layout()
plt.show()

SyntaxError: positional argument follows keyword argument (<ipython-input-11-4a27b503b426>, line 9)

In [12]:
plot_transform(ax, T_pc, s=1, lw=4)
plt.show()

NameError: name 'ax' is not defined